### ISSUE TITLE
Adding/applying black to develop branch

### ISSUE THREAD

**Issue by caleb531** [caleb531/automata#132]
@eliotwrobson Another thought for you:

Since I don't know when #129 is going to be finished, I was thinking: it might be nice to backport the black configuration out of your PR into a separate PR to be merged into `develop` branch. Then I could commit to the feature branch in #129 and run black on the modified files so that they wouldn't conflict with your type hints branch anyway.

In other words, if we can add configuration for black to the `develop` branch, and apply it to all Python files on `develop`, and apply it to all files in the open PRs, then we're all on the same page, and we won't have to worry about formatting conflicts ever again. This would also enable us to re-add the CI job sooner.

Thoughts?

**Comment by eliotwrobson** [comment]
@caleb531 I agree with the approach here. The types PR is getting big so splitting off pieces makes it more manageable, and being able to merge the style configuration stuff sooner I think will aid development.

**Comment by caleb531** [comment]
Closing this issue now that black has been applied to the `develop` branch for several days now.
