### ISSUE TITLE
Refactoring primitives that inherit from namedtuple

### ISSUE THREAD

**Issue by caleb531** [caleb531/automata#134]
@eliotwrobson Just opening an issue to follow up on our discussion about `PDAStack` (and friends), and the best way to refactor that to be cleaner without compromising the behavior/efficiency.

For reference, [here is a link](https://github.com/caleb531/automata/pull/131/files#r1155221673) to our original comment thread.

**Comment by eliotwrobson** [comment]
Looking at the discussion and the code, I kinda agree that the current inheritance and usage of `__new__` sortof is the cleanest behavior, and the `dataclass` isn't quite as clean. Let me play around with this some more and get back to this discussion.

**Comment by caleb531** [comment]
@eliotwrobson Sure, sounds good. I'll keep this issue open while you're still exploring, then.

**Comment by eliotwrobson** [comment]
Looking at the two remaining classes that can't inherit from `NamedTuple` in `typing`, it seems like both of them don't particularly benefit from this inheritance? Unless they're being hashed into sets somewhere I think it makes sense to just swap them with normal classes. Unfortunately I don't think I have time to perform this refactor (since I think this will require changing up some tests), but I don't feel particularly strongly about this either way.

**Comment by caleb531** [comment]
@eliotwrobson So some quick research seems to indicate that slot-based objects and dataclasses are notably faster than namedtuples when it comes to accessing members ([source](https://stackoverflow.com/a/70870407/560642)).

However, then that brings us back to the [my outline of the hesitations with using dataclasses](https://github.com/caleb531/automata/pull/131/files#r1157837425). But I suppose the imperative type-casting isn't all that different from a custom `__init__` method that does the same thing. It's just a matter of whether the attribute exists already or not.

And, after reviewing the documentation (e.g. [for NPDA](https://github.com/caleb531/automata/blob/develop/docs/pda/class-npda.md)), it seems like `PDAStack` and friends are not intended to be used by the end user, and are really only used internally (and any knowledge of their existence by the end user is only to deal with them as potentially part of the return values, e.g. `read_input`).

So here's a crazy idea: forget the explicit type-casting, and just assume that immutable types (like tuples) will only ever be passed. I mean, maybe that's a fine idea, or maybe that's totally inconsistent with the fact that we're type-casting in many other places in the library (like the automata subclasses). So I'm a bit on the fence with this one. But let me know your thoughts!

**Comment by eliotwrobson** [comment]
I think dropping the typecast is fine, especially if these are only meant to be used internally. I tried doing this before and it caused some test cases to fail, so it will require a bit of work to get everything working as-needed. Frankly, I'm pretty skeptical of performance being a significant concern with these classes, and these are substantially less used than some of the other parts of the library. So I'm inclined to just close this issue and cite this discussion if anyone comes in later and needs better performance / wants to make changes to the PDA or TM classes.

**Comment by caleb531** [comment]
@eliotwrobson Yep, sounds good. Closing now.
