### ISSUE TITLE
Positional vs. keyword arguments for PDAConfiguration, TMConfiguration, and TMTape

### ISSUE THREAD

**Issue by caleb531** [caleb531/automata#144]
@eliotwrobson I have a dilemma I've been running into as I refactor the *Configuration and TMTape classes. Please bear with me—it's a bit complicated:

Per my extended commit message in 4592f44af386fe15cce58058cc6a44eb5d10d40d, I've been noticing an inconsistency between the return value signatures I see in the documentation and the actual __init__ signature for those classes. For example, the DTM documentation shows the following return values:

```python
dtm.read_input_stepwise('01')
# yields:
# TMConfiguration('q0', TMTape('01', '.', 0))
# ...
```

However, there are two problems with the above:

## Problem 1: repr() output doesn't match __init__ signature

According to [the documentation for `__repr__`](https://docs.python.org/3/reference/datamodel.html#object.__repr__):

> If at all possible, this should look like a valid Python expression that could be used to recreate an object with the same value (given an appropriate environment). If this is not possible, a string of the form <...some useful description...> should be returned.

Now, this isn't a problem with `TMConfiguration` but only because `TMConfiguration` still allows for positional arguments. However, it _is_ a problem for `TMTape` because `TMTape`'s __init__ signature requires that `blank_symbol` and `current_position` be keyword-only.

## Problem 2: Consistency vs. clarity vs. brevity

But whether or not we enforce keyword arguments for `TMTape`, there is another question about the intrinsic value of keyword-only arguments, in tension with the nice brevity of positional arguments. It would also be nice to make a choice that we can adopt for all of the *Configuration and *Tape classes.

Let's look at that return value comment from the above docs:

```python
# TMConfiguration('q0', TMTape('01', '.', 0))
```

If we don't We could rewrite this a few different ways:

```python
# TMConfiguration(state='q0', tape=TMTape(tape='01', blank_symbol'.', current_position=0))
```

That's kinda long, so maybe we could eliminate the kwonly restriction for TMTape and allow for positional args:
'

```python
# TMConfiguration('q0', TMTape('01', '.', 0))
```

It's shorter which is nice, but then that creates some potential ambiguities since it's not clear that the `0` is distinct from the `'0'` that's part of the tape.

Whatever we do, I think it would be nice for it to be consistent between all the *Configuration and *Tape classes.

Anyway, I've been writing and revising this post for almost an hour, so I should probably stop and post it lol. Hopefully you get what I'm trying to explain, but feel free to ask any questions for clarification.

**Comment by eliotwrobson** [comment]
I think I get your meaning, we just want the *Configuration and *Tape classes to have simpler repr functions consistent with the positional arguments. I'm kindof leaning towards getting rid of the keyword only arguments in the cases you state here, since there are very few arguments passed into each one. I think having keyword only arguments works better in cases where there are a lot of arguments passed in (like for the DFA init function, for example). Most of these classes are for internal use anyway, and if users get confused they still have the option of using keywords.

**Comment by caleb531** [comment]
@eliotwrobson That makes sense. I agree that positional arguments are fine, so I will make the following updates:

1. Remove the keyword-only arguments requirement for `TMTape`
2. Define a custom `__repr__` for `PDAConfiguration` so that the repr output consists of entirely positional args (for brevity, and to match `TMConfiguration`). The meaning of each positional arg is already documented, anyway (e.g. in the DPDA and NPDA docs).

Closing this issue now. Thanks for the feedback!
