### ISSUE TITLE
`_get_repr_friendly_value` bug

### ISSUE THREAD

**Issue by eliotwrobson** [caleb531/automata#150]
The function raises an exception on certain inputs, specifically for minimized DFAs where `retain_names=True`.

**Comment by caleb531** [comment]
@eliotwrobson Can you please provide some code that reproduces the exception scenario?

**Comment by eliotwrobson** [comment]
@caleb531

```python
from automata.fa.dfa import DFA

thing = DFA.from_finite_language(set('abcd'), {'abcd', 'dcba'})

thing2 = thing.minify(retain_names=True)

print(thing2)
```

**Comment by caleb531** [comment]
@eliotwrobson Hello again! Sorry I've been silent on this project for the past few weeks—it's been a busy month. But I'm pleased to report that I've fixed this issue definitively. You can read my lengthy extended comment in b36d72660d699899722ba1534da4dc23ef257e4e to understand the issue. I've also added a test to verify that the test code you supplied is now fixed.

With that, I will be closing this issue.
