### ISSUE TITLE
Using epsilon vs lambda

### ISSUE THREAD

**Issue by eliotwrobson** [caleb531/automata#151]
What is the difference between `𝛌` or `ε` in an Automaton Theory context? I've seen both used, sometimes seemingly interchangeably, to represent empty string.

_Originally posted by @caleb531 in https://github.com/caleb531/automata/pull/129#discussion_r1198468618_

**Comment by eliotwrobson** [comment]
@caleb531 looking over this, I think there are a few places where the current library code is inconsistent with this theory (i.e. we use the term "lambda transition" instead of "epsilon transition"), but I'm not sure it's worth changing the API. In all instances, I think people know what is meant.

@EduardoGoulart1 @khoda81 do either of you have thoughts on this?

**Comment by khoda81** [comment]
@eliotwrobson I agree, in some references, they are used interchangeably and it is clear enough what it means...

**Comment by caleb531** [comment]
@eliotwrobson I also agree. I think as long as people are able to easily intuit what we mean (which seems to be the case)p, that's the most important thing.

**Comment by eliotwrobson** [comment]
@caleb531 Agreed. Going to go ahead and close this. If we get feedback that this is confusing for people we can revisit then.
