### ISSUE TITLE
Running the test suites in the package

### ISSUE THREAD

**Issue by mahfuz05062** [caleb531/automata#173]
One criterion for the JOSS review is: "Are there automated tests or manual steps described so that the functionality of the software can be verified?"

Can we add a way to run the test suite automatically or at least provide a guideline to run the tests manually?

This issue is part of the https://github.com/openjournals/joss-reviews/issues/5759 review.

**Comment by eliotwrobson** [comment]
So the test suite is run as part of the GitHub actions on the master branch, and can be run manually by using the `nose2` command. More details can be found here: https://github.com/caleb531/automata/blob/main/.github/CONTRIBUTING.md
