### ISSUE TITLE
Guidelines for contribution

### ISSUE THREAD

**Issue by mahfuz05062** [caleb531/automata#174]
One criterion for the JOSS review is: "Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support"

Can we include guidelines for potential contributors? Maybe a CONTRIBUTING.md file and direct the interested people there from the README.md file.

This issue is part of the https://github.com/openjournals/joss-reviews/issues/5759 review.

**Comment by eliotwrobson** [comment]
There is a CONTRIBUTING.md file in the `.github` folder: https://github.com/caleb531/automata/blob/main/.github/CONTRIBUTING.md

However, I do agree that it can be a bit hard to find. @mahfuz05062 I'll go ahead and add a link to the CONTRIBUTING.md from README.md on the front page.
