### ISSUE TITLE
Creation of non valid connection to final state when using union

### ISSUE THREAD

**Issue by gMontoyaSpeech** [caleb531/automata#179]
Hello. I have two simple DFA that should accept: "@En", "En" or "en". 
The code of those individual automata are:
 
    dfa1 = DFA(
        states={'q0', 'q1', 'q2'},
        input_symbols={'@', 'E', 'n','e'},
        transitions={
            'q0': {'@': 'q0', 'E': 'q1'},
            'q1': {'E': 'q1', 'n': 'q2'},
            'q2': {},
        },
        initial_state='q0',
        final_states={'q2'},
        allow_partial=True

    )

    dfa2 = DFA(
        states={'q0', 'q1'},
        input_symbols={'@', 'E', 'n', 'e'},
        transitions={
            'q0': {'E': 'q0', 'n': 'q1'},
            'q1': {},
        },
        initial_state='q0',
        final_states={'q1'},
        allow_partial=True

    )

    dfa3 = DFA(
        states={'q0', 'q1'},
        input_symbols={'@', 'E', 'n', 'e'},
        transitions={
            'q0': {'e': 'q0', 'n': 'q1'},
            'q1': {},
        },
        initial_state='q0',
        final_states={'q1'},
        allow_partial=True

    )

To make it easy to grasp it:
df1:
![dfa_en1](https://github.com/caleb531/automata/assets/45080861/3ccd4eda-e471-4494-9599-44369411db76)

df2:
![dfa_en2](https://github.com/caleb531/automata/assets/45080861/dbe94dc0-9fe0-4743-90e8-a0d32eb4b381)

df3:
![dfa_en3](https://github.com/caleb531/automata/assets/45080861/134b1ab9-4dc7-4d86-9c30-f63aa8b15386)

Something that it's worth noting is that even though all automata do not use the same input language even though is not needed (e.g. the dfa2 only accepts "En"  which means that "@" shouldn't be needed in that case. However, I had to add "@" in order to make the union function work out). 

However, the big problem here comes when I tried different union configurations since I always end up with a mysterious non acceptable final estate. All my attempts after using the union function are somehow accepting only the input "n", and as you can see from my automata dfa{1,2,3} that should not be acceptable. I'm adding the code of my attempts and the graphical representation of the output. I hope you can give me a hint about how I can avoid this. Thanks!!

    # Option1
    union1 = dfa1 | dfa2 | dfa3
    union1.show_diagram(path='./dfa_union1.png')

    # Option2
    union1 = dfa1 | dfa2
    union2 = union1.union(dfa3, minify=False)
    union2.show_diagram(path='./dfa_union2.png')

    # Option3
    union1 = dfa2 | dfa3
    union2 = union1.union(dfa1, minify=False)
    union2.show_diagram(path='./dfa_union3.png')

    # Option4
    union1 = dfa1.union(dfa2, minify=False)
    union2 = union1.union(dfa3, minify=False)
    union2.show_diagram(path='./dfa_union4.png')

Option1:
![dfa_union1](https://github.com/caleb531/automata/assets/45080861/eac4d832-7275-4c26-8952-1a0b3d87d7af)

Option2:
![dfa_union2](https://github.com/caleb531/automata/assets/45080861/5c2b703c-8c40-44b8-9237-4ea7f3e504e4)

Option3:
![dfa_union3](https://github.com/caleb531/automata/assets/45080861/f7d6ea39-a42c-4c62-8759-a12f89c03d36)

Option4:
![dfa_union4](https://github.com/caleb531/automata/assets/45080861/b3d68772-b3b7-4321-8a45-977127d67f2d)

**Comment by caleb531** [comment]
Interesting... @eliotwrobson can you please a look at this and let us know your thoughts?

**Comment by eliotwrobson** [comment]
@gMontoyaSpeech it looks like your DFA2 accepts the string "n", so it appears in the union. At any rate, ig you want a DFA accepting exactly the three strings you gave, you can use the from_finite_language function for DFA creation.

**Comment by gMontoyaSpeech** [comment]
Thanks @eliotwrobson for the response. To be honest I don't understand why DFA2 is accepting the string "n". Could you tell me how I could avoid that so that when using the union function I can get rid of the acceptance of this undesired string?

I also gave a try to the function you recommended but it yields to stranger behaviour. This is the code I run:


    dfa = DFA.from_finite_language (
        input_symbols={'@', 'E', 'n', 'e'},
        language={'@En','En','en'},
        as_partial=True
    )

![dfa_finite (1)](https://github.com/caleb531/automata/assets/45080861/19aa5967-630f-4a1c-bd89-ebc72c243553)

After this I tried multiple strings to check whether the acceptance/rejection was being done correctly, and I noticed that:
1.  "eeeen" is rejected  `dfa.read_input('eeeen')`. This was expected to be accepted.
2. "en" is accepted BUT `dfa.read_input_stepwise('en')` throws `["","@E","@En"]`. It was expected `["","e","en"]`. The same output is obtained if I introduce "En"

I'm not sure whether this is the correct function to use since I can see that  `from_finite_language` is not creating the self-loops I created myself in the first comment (DFA1, DFA2, DFA3). Therefore when multiple "e", "E", or "@" occur in the string it ends up being rejected. And this MUST be accepted in this case. Also, I find very confusing to see some characters the input string didn't contain as part of the stepwise output function (example 2). 

I would really love to have as output the option 4 (first post) withough the only "n" path.

**Comment by gMontoyaSpeech** [comment]
After doing some play around and getting some inspiration from `dfa.py` I decided to introduce an empty initial state to each DFA and then doing the union. This procedure indeed yields to what I was looking for (I changed the name of the states to make it easy to follow, but the accepted strings still remain the same)

    dfa1 = DFA(
        states={'', '@', 'E', 'n'},
        input_symbols={'@', 'E', 'n', 'e'},
        transitions={
            '': {'@': '@'},
            '@': {'@': '@', 'E': 'E'},
            'E': {'E':'E', 'n':'n'},
            'n': {'n':'n'}
        },
        initial_state='',
        final_states={'n'},
        allow_partial=True

    )

![dfa_en11](https://github.com/caleb531/automata/assets/45080861/ee1b905f-8518-472a-956f-86a62d0b5ba6)


    dfa2 = DFA(
        states={'', 'E', 'n'},
        input_symbols={'@', 'E', 'n', 'e'},
        transitions={
            '': {'E': 'E'},
            'E': {'E': 'E', 'n': 'n'},
            'n': {'n': 'n'}
        },
        initial_state='',
        final_states={'n'},
        allow_partial=True

    )

![dfa_en22](https://github.com/caleb531/automata/assets/45080861/517fe04f-c6ee-482c-847a-f15e22085390)

    dfa3 = DFA(
        states={'', 'e', 'n'},
        input_symbols={'@', 'E', 'n', 'e'},
        transitions={
            '': {'e': 'e'},
            'e': {'e': 'e', 'n': 'n'},
            'n': {'n': 'n'}
        },
        initial_state='',
        final_states={'n'},
        allow_partial=True

    )

![dfa_en33](https://github.com/caleb531/automata/assets/45080861/3c600770-f423-4346-bb6d-32fe1808192d)

The corresponding union code that worked for me is:

    union1 = dfa1.union(dfa2, minify=False)
    union3 = union1.union(dfa3, minify=False)

![new_opt11](https://github.com/caleb531/automata/assets/45080861/cc150ca9-89da-48ea-b613-2fc12da111e8)

However, I would like to highlight that I think the union function is not working properly. Again, I tested multiple ways to perform this operation and I surprisingly found that the union of DFA1 (@En -- capital E, unexpectedly GitHub changes to e) and DFA2 (En) yields to a very odd automaton. The union of these (`dfa1 | dfa2`) gives a DFA that only accepts "@En" (capital E) as you can see below. I hope this can be solve soon!

![new_opt2](https://github.com/caleb531/automata/assets/45080861/fde64369-8e77-4c58-a865-ac9879aca8dd)

**Comment by eliotwrobson** [comment]
@gMontoyaSpeech The final automata you gave for `dfa1 | dfa2` accepts all strings with some number (possibly zero) "@"'s, at least one "E", and at least one "n". This is indeed equivalent to the union, since your DFA1 only imposes the additional restriction that there be at least one "@", but in the union you are creating an automata that accepts the languages of both.

As I don't believe there is any issue with the library code, I am inclined to close this issue.

**Comment by gMontoyaSpeech** [comment]
Oh I see. I didn't notice it before. I was getting it wrongly. I think it is indeed correct (the final `dfa1 | dfa2`). Yes, I think you could close it. Thanks
