### ISSUE TITLE
Printing DFA status to text file

### ISSUE THREAD

**Issue by gMontoyaSpeech** [caleb531/automata#186]
Hello.  I was wondering if it's possible to print out in a text file (let's say JSON format) the parameters of a DFA. I found in another thread that at certain point a code to do the printing was written to solve other user's question (https://github.com/caleb531/automata/issues/49) but I'm not sure if this was merged in the current version of the code. If this is possible, could you tell me what function should I use?

Thanks in advance!

**Comment by caleb531** [comment]
@gMontoyaSpeech There is an `input_parameters` property, available on any `Automaton` instance, which returns a dict of the original parameters. Keep in mind that many of the parameters are converted to immutable structures upon instantiation, so if you want to modify these parameters, you'll need to convert them to mutable structures yourself (with either `dict()` or `set()`).

Here's an example of what the `input_parameters` returns:

```python
dfa1 = DFA(
    states={'q0', 'q1', 'q2'},
    input_symbols={'0', '1'},
    transitions={
        'q0': {'0': 'q0', '1': 'q1'},
        'q1': {'0': 'q0', '1': 'q2'},
        'q2': {'0': 'q2', '1': 'q1'}
    },
    initial_state='q0',
    final_states={'q1'}
)
print(dfa1.input_parameters)
# prints {'states': frozenset({'q2', 'q0', 'q1'}), 'input_symbols': frozenset({'0', '1'}), 'transitions': frozendict.frozendict({'q0': frozendict.frozendict({'0': 'q0', '1': 'q1'}), 'q1': frozendict.frozendict({'0': 'q0', '1': 'q2'}), 'q2': frozendict.frozendict({'0': 'q2', '1': 'q1'})}), 'initial_state': 'q0', 'final_states': frozenset({'q1'}), 'allow_partial': False}
```

**Comment by eliotwrobson** [comment]
Storing state names in a file can also cause issues because of differences between types in Python and what is supported in JSON. I thought about submitting some code I have that does something similar to the code in the linked issue, but ultimately decided against it because of potential type issues. The automaton types should support pickling.

**Comment by gMontoyaSpeech** [comment]
Thanks @caleb531 for letting me know about that method. I'm not sure if I came across that property when digging into the documentation. Honestly, I thought that you'd written a piece of code to output the automata's properties as they are shown in your previous post. 

@eliotwrobson At certain extend I understand that why you didn't submit the code. However, I think it would be a good idea to have it available in the repo. It's always good to have a method that allows to print in a human-reading way what the attributes of the automata are. The property that @caleb531 mentioned before is quite a good starting point. However, the "frozendict" or "frozen" makes it convoluted to understand when sharing such output with people that are not familiar with this module. if such method is added, then it certainly should be written in the documentation the caveat about its "displaying" intent (ext format only) instead of making its serialization.

Thank you all for your input!

**Comment by eliotwrobson** [comment]
If a function like this is just meant for displaying, then most of the automaton classes have repr methods that already do this.
