### ISSUE TITLE
Concatenation of DFA

### ISSUE THREAD

**Issue by gMontoyaSpeech** [caleb531/automata#192]
Hello,

I went though the documentation and noticed that concatenation is only available for the NFA class. I currently have two DFA instances and I need to concatenate them. Is there any way to achieve this with the current code or do I have to implement the concatenation method for the DFA class?

Thanks!

**Comment by eliotwrobson** [comment]
I don't think there's a way to efficiently compute the concatenation of two DFAs. However, with the existing code, you can convert both of the DFAs you have to NFAs, concatenate them, then convert the result back to a DFA. Would that work?

**Comment by gMontoyaSpeech** [comment]
Oh I didn't know that such conversion wasn't straightforward. Could you tell me where I can find the documentation about converting a DFA to NFA and then NFA to DFA?
Thanks in advance!

**Comment by eliotwrobson** [comment]
Take a look at the docs pages here:
https://github.com/caleb531/automata/blob/main/docs/fa/class-dfa.md#dfafrom_nfacls-nfa-retain_namesfalse-minifytrue
https://github.com/caleb531/automata/blob/main/docs/fa/class-nfa.md#nfafrom_dfacls-dfa

**Comment by caleb531** [comment]
I haven't seen any new activity on this thread, so @gMontoyaSpeech, I assume the documentation links were what you needed. Therefore, closing this thread, but would be happy to reopen if you still need clarification or anything.
