### ISSUE TITLE
DFA: `maximum_word_length` complexity scales with number of final states

### ISSUE THREAD

**Issue by Tagl** [caleb531/automata#202]
Since switching to networkx there seems to have been a degradation in speed for DFAs with a large number of final states.
For example I have one with 3348 final states and 11312 states in total.
The construction of coaccessible_nodes will run 3348 Breadth First Searches instead of running one with 3348 sources.
This results in the time complexity being O(NM) in the worst case.
This means that the check takes a full minute to run in my case which is not reasonable at this size.

Looking at networkx there isn't any direct way of changing our code to simply passing in multiple sources.
I'm honestly shocked that this isn't part of the interface.

https://github.com/caleb531/automata/blob/13e5c1b5bf1d92522eb83e914ad946552b77aaf7/automata/fa/dfa.py#L1656-L1658

**Comment by eliotwrobson** [comment]
Isn't this fairly straightforward to circumvent? We just need to add a dummy node that all final states link to.

**Comment by Tagl** [comment]
> Isn't this fairly straightforward to circumvent? We just need to add a dummy node that all final states link to.

That would be one way. We could also patch networkx so that this is supported. I'm testing the speed difference now.

**Comment by eliotwrobson** [comment]
That would be a useful addition to networkx, but that project is huge so I wouldn't expect that to get merged anytime soon. Might be worth submitting an issue though.

**Comment by Tagl** [comment]
Another place where the same code is used:
https://github.com/caleb531/automata/blob/13e5c1b5bf1d92522eb83e914ad946552b77aaf7/automata/fa/dfa.py#L1414-L1416

**Comment by eliotwrobson** [comment]
Yeah, that pattern appears in a couple places. @Tagl could you submit a PR? No worries if it's a WIP.

**Comment by Tagl** [comment]
I made my change in networkx as well so I can't submit a PR just yet.

**Comment by eliotwrobson** [comment]
Sounds reasonable. @Tagl is there a way to do this cleanly without changes to networkx? The more I think about it, the more it's weird they don't allow multi-source and multi-sink reachability queries.

**Comment by Tagl** [comment]
This looks (practically) equivalent to the changes I made, but with fixes in additional places in `dfa.py`.

**Comment by eliotwrobson** [comment]
Closing as this was merged.
