### ISSUE TITLE
statement of python 3.12 support

### ISSUE THREAD

**Issue by phildong** [caleb531/automata#211]
When trying to reproduce the tests locally, I hit `TypeError: type 'typing.TypeVar' is not an acceptable base type`, which seem to be a known issue with python 3.12: https://github.com/python/typing_extensions/issues/243

I notice some python version spec in `.github/workflows` and `.python-version` but they're easy to miss (maybe it's just me). So maybe consider either investigate python 3.12 support or stating supported version (<=3.11) more explicitly in README?

**Comment by caleb531** [comment]
@phildong After some troubleshooting, it appears we have this fixed on the `develop` branch, but not on `main`. if you would like to unblock yourself, please use the `develop` branch until I publish a release to PyPI (planning to do that soon, if not today).

cc @eliotwrobson

**Comment by eliotwrobson** [comment]
@caleb531 as part of this support, we should add classifiers that denote which versions of Python have been supported by the package: https://pypi.org/classifiers/

Then, we can have the badge on the readme reflect this.

**Comment by caleb531** [comment]
@eliotwrobson It looks like we just recently added said classifiers via c8b11489a33739a30fd4572c02cacf69a3d6bd7d. So I think we're covered there.

With that, I have a draft of the release notes all ready. @eliotwrobson if you could please review and give a quick sign-off on releasing, I can publish a new minor release with these fixes (and the Aho-Corasick functionality) today.

**Comment by eliotwrobson** [comment]
@caleb531 sure! Are these stored as a draft on the GitHub release notes?

**Comment by caleb531** [comment]
@eliotwrobson Yes, that's where I have been trying to keep drafts of the release notes going forward.

**Comment by eliotwrobson** [comment]
@caleb531 The release notes look good! I say go ahead 🚀

**Comment by caleb531** [comment]
Okay, Automata v8.3.0 is published, fixing Python 3.12 support and adding a few other features/fixes:
https://github.com/caleb531/automata/releases/tag/v8.3.0
https://pypi.org/project/automata-lib/

@phildong You should be able to run tests now off the latest `main` branch. Just remember to `git pull` and re-run `pip install -r requirements.txt`.

Once you confirm, I'll close this issue.

**Comment by caleb531** [comment]
@phildong Can you please confirm if you are able to run the tests now under Python 3.12 (after following my steps above)?

**Comment by phildong** [comment]
Hey @caleb531 thanks for making this happen! I can confirm all tests work with python 3.12 on my side now.
