### ISSUE TITLE
demonstration of processing of large input

### ISSUE THREAD

**Issue by phildong** [caleb531/automata#213]
The README mentioned optimized algorithm for processing of large inputs. It would be awesome to include some example/benchmarking demonstrating the capability in this regard.

**Comment by caleb531** [comment]
That's a great idea! @eliotwrobson, is this something you would be able to work on?

**Comment by eliotwrobson** [comment]
@caleb531 I should be able to take a look. The performance claims aren't with respect to any huge benchmarks or anything, so I can add something that randomly generates large examples for minimization to the docs.

**Comment by phildong** [comment]
I think any quantitative benchmark would be helpful here.
Just want to give some specific details regarding what's "capable of processing large input", so people can at least have an idea and potentially compare to other packages.

**Comment by eliotwrobson** [comment]
@phildong I have added the performance examples in #217. Please let me know what you think, or if there are other possible examples that you think might be helpful.

**Comment by eliotwrobson** [comment]
Performance based examples have been added to the documentation in the develop branch! Closing.
