### ISSUE TITLE
No visualization despite installed dependency

### ISSUE THREAD

**Issue by mario-hess** [caleb531/automata#216]
I installed automata lib and the visual extra, but the visualization of the automata does not show up. Neither if executed through a python file, nor through jupyter lab. 

System : Arch Linux

**Comment by caleb531** [comment]
@mario-hess What do you mean? Are you trying to generate an image of an automata with `show_diagram`, but the generated image is blank? Or is it something else? Anything minimal code you could provide to reproduce the issue would be helpful.

@eliotwrobson Could you please chime in with any input you have?

**Comment by mario-hess** [comment]
Exactly, I'm trying to generate an image with `show_diagram`, but no image is being generated. 

This is the code I'm trying to run:

```
from automata.fa.dfa import DFA
from visual_automata.fa.dfa import VisualDFA

'''
This deterministic finite automaton defines a regular language
where an input string is valid if and only if the number of 1s is odd.
'''
vdfa1 = VisualDFA(
    states={'q0', 'q1', 'q2'},
    input_symbols={'0', '1'},
    transitions={
        'q0': {'0': 'q0', '1': 'q1'},
        'q1': {'0': 'q0', '1': 'q2'},
        'q2': {'0': 'q2', '1': 'q1'}
    },
    initial_state='q0',
    final_states={'q1'}
)

vdfa1.show_diagram()
print(vdfa1.input_check('10101')) # valid
print(vdfa1.input_check('1010'))  # invalid
```

Here is a screenshot of the output:
![automata_screenshot](https://github.com/caleb531/automata/assets/53190466/d3b885c4-940b-434b-a478-42493c7adb0d)

**Comment by eliotwrobson** [comment]
@mario-hess I think I see the issue, you're calling `show_diagram` on the `VisualDFA` class, not the DFA class. The `VisualDFA` class is not even part of this package (but rather, the visual automata package, which has since been deprecated). Try creating a vanilla DFA and see if that works for you.

**Comment by mario-hess** [comment]
Thank you very much, it works!
