### ISSUE TITLE
Example request

### ISSUE THREAD

**Issue by irisdyoung** [caleb531/automata#221]
In the provided examples at https://caleb531.github.io/automata/examples/fa-examples/ it would be helpful if we could get

- all the necessary context to reproduce the examples (e.g. definitions for the nfa1 and nfa2 referenced under "Subset for NFAs")
- expected outputs to compare against

Personally I would prefer encapsulation in example scripts structured so that we can import and reuse those objects. Sticking the entire first example code block in a file will produce a valid script that only does one thing, whereas wrapping the input loop in a function definition would allow `my_dfa` to be imported into the next example. Similarly, making a `words_within(edit_distance)` function or something similar would give the new user something to play with a bit more interactively.

(These are suggestions to consider, not demands.)

**Comment by eliotwrobson** [comment]
I think adding some encapsulation and making the examples a little more narrative driven is a good move 👍🏽

**Comment by eliotwrobson** [comment]
Examples in documentation have been updated on the develop branch, closing.
