### ISSUE TITLE
Visualization methods called from command line installation

### ISSUE THREAD

**Issue by irisdyoung** [caleb531/automata#222]
Examining the object `my_dfa` from the first example directly (no `str` or `dir` or anything else) throws an error in the command line only installation (latest, on python 3.12.3, on mac):

`ImportError: Missing visualization packages; please install coloraide and pygraphviz.`

Is this for sure what you want? It also does return the `str` representation afterward, so it seems like the error could be downgraded to a warning that you're operating without visualization capabilities, and a pointer to the installation option with the necessary dependencies. Separate issue incoming on that note...

**Comment by caleb531** [comment]
@irisdyoung @eliotwrobson I'm not sure I understand the issue here. I `pip install automata` into a fresh virtualenv (Python 3.12.3 on macOS Sonoma, using Mac terminal), and then run the first example from the [FA Examples](https://caleb531.github.io/automata/examples/fa-examples/) page, I am able to run the machine without error.

```py
# example1.py
from automata.fa.dfa import DFA

# DFA which matches all binary strings ending in an odd number of '1's
my_dfa = DFA(
    states={'q0', 'q1', 'q2'},
    input_symbols={'0', '1'},
    transitions={
        'q0': {'0': 'q0', '1': 'q1'},
        'q1': {'0': 'q0', '1': 'q2'},
        'q2': {'0': 'q2', '1': 'q1'}
    },
    initial_state='q0',
    final_states={'q1'}
)

try:
    while True:
        if my_dfa.accepts_input(input('Please enter your input: ')):
            print('Accepted')
        else:
            print('Rejected')
except KeyboardInterrupt:
    print('')
```

**Comment by lwasser** [comment]
[linking this to our review ](https://github.com/pyOpenSci/software-submission/issues/152) - friends can you please link any issues / pr's related to the review back to the review issue so we have a traceable review? many many thanks!! these issues and discussion are fantastic!

**Comment by caleb531** [comment]
@eliotwrobson Agreed to close as not planned—we can always reopen if need be.
