### ISSUE TITLE
Possibly update GitHub Link?

### ISSUE THREAD

**Issue by eliotwrobson** [caleb531/automata#225]
As was pointed out [in this comment](https://github.com/pyOpenSci/software-submission/issues/152#issuecomment-2155293765), it might be a good idea to change the GitHub link from the pypi page to the documentation site. I'm not totally sure what the standard practice is, but I guess it's down to personal preference. What do you think @caleb531? I don't have super strong feelings either way.

**Comment by caleb531** [comment]
@eliotwrobson Are you referring to the GitHub website link in the About section of the repository? If this i what you're referring to, then I am inclined to agree. The PyPI page really (and also quite literally) just contains the same info as the README, anyway.

<img width="633" alt="Screenshot 2024-06-14 at 3 32 36 PM" src="https://github.com/caleb531/automata/assets/872474/34cb6182-0ac3-472a-ae83-c4a20f723318">
<img width="326" alt="Screenshot 2024-06-14 at 3 32 26 PM" src="https://github.com/caleb531/automata/assets/872474/4b9c719c-c2fb-487c-8351-d2e6cd10d65e">

**Comment by caleb531** [comment]
@eliotwrobson It seems clear now that's what you meant, so I went ahead and updated it! Closing this issue. Please feel free to let pyOpenSci know that we've updated this now.
