### ISSUE TITLE
Unicode characters with regexp ?

### ISSUE THREAD

**Issue by kunchtler** [caleb531/automata#232]
Hello all,
Is there a reason why general unicode characters are not usable with regexp ?
I'm using this library to compute the regular expressions of automata with large alphabet (> 100 letters sometimes) so it would be nice to have this feature.
(I seem to have it working on my side by changing a single line of code with all tests still passing)
Thanks !

**Comment by eliotwrobson** [comment]
This had to do with the regex we used to do parsing. If you have a change that enables using any Unicode character, we'd be happy to review and accept a pull request!

**Comment by eliotwrobson** [comment]
PR was merged to develop, should go out with the next deploy.
