### ISSUE TITLE
Automatat PDA error: "The automaton entered a configuration for which no transition is defined (q0, a, 0)"

### ISSUE THREAD

**Issue by Panchoclo01** [caleb531/automata#34]
Using the PDA library, I get a code error with reference to transitions. "The automaton entered a configuration for which no transition is defined (q0, a, 0)".

(Attached code in paste.org)
https://www.paste.org/117966

Image of the PDA I made at https://automatonsimulator.com
![image](https://user-images.githubusercontent.com/86635704/123720355-defceb80-d851-11eb-9ea1-f7c1129b5337.png)

Image with the error
![image](https://user-images.githubusercontent.com/86635704/123720765-d78a1200-d852-11eb-9e99-678cd9ad0fc7.png)

**Comment by caleb531** [comment]
Thanks, @Panchoclo01. Can you please provide the code for the PDA that you are trying to read input into? (perhaps by printing it out in Python)

**Comment by caleb531** [comment]
@Panchoclo01 My apologies; I see you provided the code via paste.org; I missed the code snippet.

I am looking into this now.

**Comment by caleb531** [comment]
@Panchoclo01 I've identified the issue: you it's because you're defining two `'a'` keys in your dictionary:

**Don't do this:**
```python
'q0':{
    'a': {'0': ('q0', ('1', '0'))},
    'a': {'1': ('q0', ('1', '1'))},
```

**Do this:**
```python
'q0':{
    'a': {
        '0': ('q0', ('1', '0')),
        '1': ('q0', ('1', '1')
    )
},
```
