### ISSUE TITLE
PDA automata error: "A symbol transition is adjacent to a lambda transition for this DPDA."

### ISSUE THREAD

**Issue by Panchoclo01** [caleb531/automata#35]
When transforming the automata to code, the value I get back is an error.
A symbol transition is adjacent to a lambda transition for this DPDA

Here is the code at paste.org
https://www.paste.org/118004

And here the automata image.
![image](https://user-images.githubusercontent.com/86635704/123899639-93bc0900-d935-11eb-95d4-ce1931082f65.png)

(something to clarify: 
![image](https://user-images.githubusercontent.com/86635704/123899954-2eb4e300-d936-11eb-957c-4a4d434588cf.png)
In this case, g,-/- is the same as g,2/_
Why this happend? i'm very sure that the automata is correct

**Comment by caleb531** [comment]
It's because your syntax for the single-element tuples is incorrect. Every ('') should be a ('',) in order to be a proper tuple.

Regards,
Caleb

**Comment by Panchoclo01** [comment]
But in that case, i just wanna pops the symbols from stack, the same syntax where you show in your post.
![image](https://user-images.githubusercontent.com/86635704/123971975-7b290e80-d988-11eb-9de4-441d71674f03.png)

No do this
![image](https://user-images.githubusercontent.com/86635704/123972760-25a13180-d989-11eb-9f61-09e829116149.png)

Regards

**Comment by caleb531** [comment]
Yes, but this is not an API issue. This is a matter of Python syntax.

The ('q2', '') structure you see in the documentation is a tuple (surrounded by parentheses). When a tuple contains only one item, it must end with a trailing comma.

In other words, this is valid:
('',)

Whereas this is not valid:
('')

Does that make more sense? I know it's kinda weird syntax, but this is just how Python works.

Regards,
Caleb

**Comment by Panchoclo01** [comment]
Thank you so much, now is working

Regards
