### ISSUE TITLE
Unable to install 5.0.0 with pip

### ISSUE THREAD

**Issue by jasonxia17** [caleb531/automata#39]
When I run `pip install automata-lib==5.0.0`, I get the following error message:

```
ERROR: Could not find a version that satisfies the requirement automata-lib==5.0.0 (from versions: 5.0.0.macosx-10.15-x86_64, 1.0.0.post1, 1.0.0.post2, 1.0.0.post3, 1.0.0.post4, 2.0.0, 2.0.1, 2.1.0, 3.0.0, 3.1.0, 3.1.0.post1, 4.0.0, 4.0.0.post1)
ERROR: No matching distribution found for automata-lib==5.0.0
```

**Comment by caleb531** [comment]
@jasonxia17 Good catch, so sorry about that. I forgot to build the wheel distribution for v5—how embarrassing 😳 .  I've pushed it up now, and confirmed I can successfully run:

```sh
pip install automata-lib==5.0.0
```

Please give it another go and let me know how it works. Again, sorry about that—how embarrassing. 😳

**Comment by jasonxia17** [comment]
Thanks, it works now!
