### ISSUE TITLE
Performance improvement for equality checking

### ISSUE THREAD

**Issue by eliotwrobson** [caleb531/automata#47]
The `__eq__` function in the DFA class uses the symmetric difference between both DFAs, which is an O(n^2) time algorithm (and requires creating an auxiliary DFA). The Hopcroft-Karp algorithm doesn't require creating the auxiliary data structures, but requires the use of a union find. I think it's possible to copy in the code from a generic Python Union-Find, but the `networkx` package has an implementation. Is it too much to introduce this dependency? Any generic union find should work.

**Comment by caleb531** [comment]
@eliotwrobson How complex/lengthy is the Python implementation of the algorithm? If it is not too bad, I would definitely prefer to minimize project dependencies.

But otherwise, if the algorithm is too sophisticated, I may consider `networkx`, especially if other library methods could also utilize it.

**Comment by eliotwrobson** [comment]
The Python implementation isn't _too_ bad, (you can view [here](https://networkx.org/documentation/stable/_modules/networkx/utils/union_find.html)) but `networkx` enabled us to shorten the implementation for a bunch of other functions, so I think it's worth including. (For example, the `isempty` function can have a bunch of it's helper functions replaced by `networkx` calls).

**Comment by caleb531** [comment]
@eliotwrobson A bunch of other functions? I like the sound of that.

Very well, then! I approve the addition of `networkx` as a dependency. Just please remember that when you submit your next PR to add the dependency, you'll need to add `networkx` to the `dependencies` array in `pyproject.toml` (with whatever version constraint you deem appropriate).

Thanks again!

**Comment by caleb531** [comment]
@eliotwrobson Okay, #48 has been merged to `develop`. Can you please submit PRs for the other methods you thought could be refactored to leverage `networkx`?

**Comment by eliotwrobson** [comment]
Sounds good. I'll make one for all the DFA functions first. The one for the NFA functions might involve some of the new regex parsing stuff, and I want a chance to look at that before integrating the changes.

**Comment by eliotwrobson** [comment]
Closing since PRs for equality function and networkx dependency have been merged.
