### ISSUE TITLE
NFA->DFA: when initial state has epsilon transition

### ISSUE THREAD

**Issue by dengl11** [caleb531/automata#5]
Thanks for the awesome library!

I think that there might be a bug for `DFA.from_nfa`.  When the initial state has epsilon transition, the initial states for the NFA do not include other DFA states that can be reached from the DFA initial state via epsilon transition.

Here is a script that I tested:

···
nfa = NFA(
    states={'q0', 'q1', 'q2'},
    input_symbols={'a', 'b'},
    transitions={
        'q0': {'': {'q2'}},
        'q1': {'a': {'q1'}},
        'q2': {'a': {'q1'}}
    },
    initial_state='q0',
    final_states={'q1'}
)

print("NFA: {}".format(nfa.read_input('a')))

dfa = DFA.from_nfa(nfa)  # returns an equivalent DFA
print("DFA: ")
print("Initial State: {}".format(dfa.initial_state))
print(dfa.read_input('a') )
···

And here is the output:
```
NFA: {'q1'}
DFA:
Initial State: {q0}
Traceback (most recent call last):
  File "nfa.py", line 23, in <module>
    print(dfa.read_input('a') )
  File "/usr/local/lib/python3.6/site-packages/automata/base/automaton.py", line 34, in read_input
    for config in validation_generator:
  File "/usr/local/lib/python3.6/site-packages/automata/fa/dfa.py", line 105, in read_input_stepwise
    self._check_for_input_rejection(current_state)
  File "/usr/local/lib/python3.6/site-packages/automata/fa/dfa.py", line 89, in _check_for_input_rejection
    current_state))
automata.base.exceptions.RejectionException: the DFA stopped on a non-final state ({})
```

**Comment by caleb531** [comment]
@dengl11 Closing this issue, since the corresponding PR has been merged. :)
