### ISSUE TITLE
Adding user input

### ISSUE THREAD

**Issue by alatorre-sebastian** [caleb531/automata#81]
How to add user input to a **dfa** or **nfa** ?

**Comment by caleb531** [comment]
@alatorre-sebastian It should be all documented in the README. Basically, you need to import the `DFA` or `NFA` class, instantiate your object, then call either the `read_input` or `read_input_stepwise` method on it. The README should have examples of this—see the links below:

https://github.com/caleb531/automata#class-dfafa
https://github.com/caleb531/automata#class-nfafa

**Comment by alatorre-sebastian** [comment]
TRhank you very much.
How about states, input symbols and transitions user inputs

**Comment by caleb531** [comment]
@alatorre-sebastian It's all in the README. I would encourage you to start reading from the DFA section I linked to above (also pasted below for convenience):
https://github.com/caleb531/automata#class-dfafa
