### ISSUE TITLE
New Construction Idea

### ISSUE THREAD

**Issue by eliotwrobson** [caleb531/automata#87]
@caleb531 was poking around online and found this blog post talking about constructing NFAs that recognize words within a given edit distance of a target word, along with some other cool utilites: http://blog.notdot.net/2010/07/Damn-Cool-Algorithms-Levenshtein-Automata

I think it could potentially be easy to integrate some of these ideas as well, since the blog post provides worked out examples (that could be used as tests) and code implementing these in Python (that should be easy to adapt). What do you think?

EDIT:
After more googling I guess this is like a thing or something, because here's two more blog posts implementing faster algorithms (in Python!):

https://julesjacobs.com/2015/06/17/disqus-levenshtein-simple-and-fast.html
https://fulmicoton.com/posts/levenshtein/

**Comment by eliotwrobson** [comment]
The code has been adapted in the current PR #90. Some of the more efficient direct DFA constructions use more involved algorithms, but they basically do the same thing of determinizing the DFA on the fly from an implicit description of the NFA (and other optimizations with respect to parameters).

The only interesting thing that I couldn't get working was an algorithm to get the lexicographically next string in a DFA, but this isn't really that important (since we already have functions that enumerate the language of the DFA directly, and those are very efficient). Plus, this algorithm is very tricky to implement.

**Comment by caleb531** [comment]
@eliotwrobson Sorry I never replied to this. I did see this, and already left you my comments on #90.  I'm fine with adding algorithms like that—I just won't necessarily have as much time anymore to implement them myself.

**Comment by eliotwrobson** [comment]
@caleb531 likewise. It doesn't really matter since you can accomplish basically the same thing by using the functions that enumerate all input strings (as those are fast even for very large DFAs).

**Comment by Tagl** [comment]
> EDIT: @Tagl something you could take a look at if you're feeling up to it (but no pressure of course).

Could you provide me with an example so I'm sure what you're asking for.
As I understand it you mean a function call like
```python
dfa.successor('00001')
```
which would then return maybe `000010` or `00010` or even '1'.

**Comment by eliotwrobson** [comment]
Yes @Tagl basically what you said. There's more details in the first blog post in the original issue, but basically a function that, given a query string, gets the lexicographically next string contained in the DFA.

**Comment by Tagl** [comment]
I have an idea how to do this, so I'll take a look at implementing this next.
A matching predecessor would make sense too.
I think this is useful, it allows for a different type of generation than the current `__iter__` method, but I think the current method of iterating is more practical in general.
