### ISSUE TITLE
Rename Automaton.attributes()

### ISSUE THREAD

**Issue by caleb531** [caleb531/automata#88]
@eliotwrobson So you probably recall that I recently added an `Automaton.attributes()` method to retrieve all the public (non-underscore-prefixed) attributes on an Automaton instance, inspired by @Tagl's recent PR. However, I find the current name a little ambiguous, since some members that are technically considered attributes are excluded from the resulting `dict`.

Here are some alternative ideas I have, mostly based on the observation that every public Automaton attribute also appears to be an input parameter to its respective `__init__`:

- `parameters`
- `input_parameters`
- `input_params`

I'm also considering if this would be better as a `@property` rather than a method. I like the brevity of omitting any verbiage, but on the flip side, want to property communicate that this method isn't an input parameter in itself.

Thoughts?

**Comment by eliotwrobson** [comment]
@caleb531 I think listing `input_parameters` as a property is a good idea, it's really just a constant fixed at the class level and there's no need to use a function to return it (there's no computation going on). While you're at it, it's probably a good idea to go ahead and use `__slots__` on the automata classes, since they're all immutable now.

**Comment by caleb531** [comment]
@eliotwrobson Oh, I totally forgot about `__slots__`! Although `__dict__` seems to disappear when I tried adding it to `DFA` just now. So 

As for `input_parameters` as a property, sounds good to me.

**Comment by eliotwrobson** [comment]
@caleb531 Yes, `__dict__` gets removed if you set `__slots__` by default. If you need to access `__dict__` for a method, you can add `__dict__` to the slots list. See: https://towardsdatascience.com/understand-slots-in-python-e3081ef5196d

**Comment by caleb531** [comment]
@eliotwrobson That's a thought, but I think I'd rather just use `input_parmeters` with an updated comprehension:

```python
{
    attr_name: getattr(dfa, attr_name)
    for attr_name in dfa.__slots__
}
```

**Comment by caleb531** [comment]
@eliotwrobson Closing this now because the related PR has been merged. Thanks for your feedback on this.
